config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  devise_for :users
  resources :users

  resources :posts do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  resources :conversations do
  resources :messages
 end

  root to: "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true

  belongs_to :user

  has_many :comments, as: :commentable
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base

  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.to_date
  end
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord

  has_many :comments, dependent: :destroy, as: :commentable
  belongs_to :user

  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :image_upload, styles: {
    croppable: '600x600>'
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :image_upload, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy


  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  # def self.create_with_omniauth(auth)
  #   create! do |user|
  #     user.provider = auth['provider']
  #     user.uid = auth['uid']
  #     user.name = auth['info']['nickname']
  #     user.image = auth['info']['image']
  #     user.fullname = ""
  #     user.contact = ""
  #     user.bio = ""
  #   end
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable

  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.new comment_params
    @comment.user = current_user
    @comment.save
    redirect_to :back
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end


  private

    def comment_params
      params.require(:comment).permit(:content, :user_id)

    end

    def find_commentable
      @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
      @commentable = Post.find_by_id(params[:post_id]) if params[:post_id]

    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  # before_action :authenticate_user

  def index
    @users = User.all
    @conversations = Conversation.all
  end

  def create
    data = params

    if Conversation.between(current_user.id,params[:recipient_id])
      .present?
      @conversation = Conversation.between(current_user.id,
      params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params(data))
    end

    redirect_to conversation_messages_path(@conversation)
  end


private

  def conversation_params data
    params = ActionController::Parameters.new({
      conversation: {
        sender_id: current_user.id,
        recipient_id: data[:recipient_id].to_i
      }
      })

    params.require(:conversation).permit(:sender_id, :recipient_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages
      if @messages.length > 10
      @over_ten = true
      @messages = @messages[-10..-1]
    end

    if params[:m]
      @over_ten = false
      @messages = @conversation.messages
    end

    if @messages.last
      if @messages.last.user_id != current_user.id
        @messages.last.read = true;
      end
    end

    @message = @conversation.messages.new
    end

  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end

private

 def message_params
  params.require(:message).permit(:body, :user_id)
 end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.save
    redirect_to "/"
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to "/"
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.user == current_user
      @post.destroy
    else
      flash[:alert] = "Only the author of the post can do that!"
    end

    redirect_to "/"
  end



  private

  def post_params
    params.require(:post).permit(:title, :content, :image_upload)
  end



end

app/controllers/sessions_controller.rb
# class SessionsController < ApplicationController
#   def create
#     auth = request.env["omniauth.auth"]
#     user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)

#     session[:user_id] = user.id
#     redirect_to root_url, :notice => "Signed in!"
#   end

#   def destroy
#     session[:user_id] = nil
#     redirect_to root_url, :notice => "Signed out!"
#   end
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def destroy
    User.destroy(params[:id])
    session[:user_id] = nil
    redirect_to(:back)
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to(:user)
  end

  private
    def user_params
    params[:user].permit(:name, :fullname, :contact, :bio, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<li>
  <div class="commentBox">
    <p class="lead"><%= comment.content %></p>
    <% if comment.user.fullname == "" || comment.user.fullname == nil %>
      <h6>By <a href="/users/<%=comment.user['id']%>"><%= comment.user.email %></a> | Submitted <%= time_ago_in_words(comment.created_at) %> ago</h6>
    <%else%>
      <h6>By <a href="/users/<%=comment.user['id']%>"><%= comment.user.fullname %></a> | Submitted <%= time_ago_in_words(comment.created_at) %> ago</h6>
    <%end%>

    <% if current_user %>
      <% if current_user.id == comment.user_id %>
        <%= link_to "Edit", edit_post_comment_path(@post, comment) %> |
        <%= link_to "Delete", post_comment_path(@post, comment), method: :delete %>
      <%end%>
    <%end%>

    <% if current_user %>
      <div class="addReply">
        <%= form_for [comment, Comment.new] do |f| %>
          <div class="emoji-picker-container">
            <%= f.text_area :content, placeholder: "Add a Reply", class: 'form-control', data: {emojiable: true} %>
          </div><br>
          <%= f.submit "Reply", :class => "btn btn-default" %>
        <% end %>
      </div>
    <%end%>

  </div>

  <ul>
      <%= render partial: 'comments/comment', collection: comment.comments %>
  </ul>

</li>

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <div class="emoji-picker-container">
  <%= f.text_area :content, class: 'form-control', data: {emojiable: true} %><br>
  </div><br>
  <%= f.submit 'Update Comment', :class => "btn btn-default" %>
<% end %>

app/views/comments/edit.html.erb
<%= render "posts/navbar" %>

<div class="container">
  <%= link_to "&larr; Back".html_safe, posts_path %>
  <h3>Edit Comment</h3>
  <%= render "form" %>
</div>

app/views/comments/new.html.erb
<%= render "posts/navbar" %>


<div class="container">
  <%= link_to "&larr; Back".html_safe, posts_path %>
  <% if current_user %>
    <h2>New Comment</h2>
    <%= render "form" %>
  <%else%>
    <h3><%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %> to create a new comment!</h3>
  <%end%>

</div>

app/views/conversations/_form.html.erb
<%= form_tag("/conversations", method: "post") do %>

  <h6><%= label_tag(:recipient_id, "Choose a user") %></h6>

  <%= select_tag(:recipient_id, options_from_collection_for_select(User.where.not(id: current_user.id), 'id', 'email'), {class: 'form-control'}) %><br>
  <%= submit_tag "Message User", :class => "btn btn-default" %>

<% end %>

app/views/conversations/index.html.erb
<%= render "posts/navbar" %>

<div class="container">

  <%= link_to "&larr; Back".html_safe, posts_path %>

  <% if current_user %>

  <h3>Inbox:</h3>

  <% @conversations.each do |conversation| %>
    <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
      <% if conversation.sender_id == current_user.id %>
        <% recipient = User.find(conversation.recipient_id) %>
      <% else %>
        <% recipient = User.find(conversation.sender_id) %>
      <% end %>

      <% if recipient.fullname == "" || recipient.fullname == nil %>
        <h5><%= link_to recipient.email, conversation_messages_path(conversation)%></h5>
      <% else %>
        <h5><%= link_to recipient.fullname, conversation_messages_path(conversation)%></h5>
      <% end %>
    <% end %>
  <% end %>

  <div class="divider"></div>

  <h3>All Users</h3>


  <%=render 'form'%>

  <%else%>
    <h3><%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %> to create send messages!</h3>
  <%end%>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thinx</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <!-- Latest compiled and minified CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/paper/bootstrap.min.css" rel="stylesheet" integrity="sha384-awusxf8AUojygHf2+joICySzB780jVvQaVCAt1clU3QsyAitLGul28Qxb2r1e5g+" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

app/views/messages/index.html.erb
<%= render "posts/navbar" %>

<div class="container messages">

  <%= link_to "&larr; Back".html_safe, conversations_path %>

  <% if @over_ten %>
    <%= link_to 'Show Previous', '?m=all' %>
  <% end %>

  <% @messages.each do |message| %>
    <% if message.body %>
      <% user = User.find(message.user_id) %>

      <% if current_user.id == message.user_id %>
        <h5 class="current">Me: </h5>
      <%else%>
        <%if user.fullname = "" || user.fullname = nil %>
          <h5><%= user.email %></h5>
        <%else%>
          <h5><%= user.fullname %></h5>
        <%end%>
      <%end%>

      <h6>Sent <%= message.message_time %></h6>
      <i class="right triangle icon"></i>
      <p class="lead"><%= message.body %></p>
    <% end %>
  <% end %>

  <%= form_for [@conversation, @message] do |f| %>
    <div class="field emoji-picker-container">
      <%= f.text_area :body, class: "form-control", data: {emojiable: true} %>
    </div>
    <%= f.text_field :user_id, value: current_user.id, type: "hidden" %><br>
    <%= f.submit "Add Reply", :class => "btn btn-default" %>
  <% end %>

</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %><br>
  <div class="emoji-picker-container">
    <%= f.text_field :title, class: 'form-control', data: {emojiable: true} %><br>
  </div><br>
  <%= f.label :content %><br>
  <div class="emoji-picker-container">
    <%= f.text_area :content, class: 'form-control', data: {emojiable: true} %><br>
  </div><br>
  <%= f.label :Add_image %><br>
  <%= f.file_field :image_upload %><br>
  <%= f.submit "Create Post", :class => "btn btn-default" %>
<% end %>

app/views/posts/_navbar.html.erb
 <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">CATSOSPHERE</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">ALL POSTS</a></li>
        <li><a href="/posts/new">NEW POST</a></li>
        <li><a href="/users">ALL USERS</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">PROFILE<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/users/<%=current_user.id%>">View Profile</a></li>
            <li><a href="/conversations">Messages</a></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>

      <% else %>

        <li><%= link_to "SIGN UP", new_user_registration_path %></li>
        <li><%= link_to "SIGN IN", new_user_session_path %></li>

      <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/posts/edit.html.erb
<%= render "navbar" %>

<div class="container post">
  <%= link_to "&larr; Back".html_safe, post_path %>
  <% if current_user %>
    <% if @post.created_at < 1.hour.ago %>
      <h3>Sorry, you've exceeded the time limit for editing!</h3>
    <%else%>
      <h2>Edit Post</h2>
      <%= render "form" %>
    <%end%>

  <%else%>
    <h2>Only the author of this post can edit it.</h2>
  <%end%>
</div>

app/views/posts/index.html.erb
<%= render "navbar" %>

<div class="container center">
  <% @posts.each do |post| %>
    <article>
      <h3><%= link_to post.title, post_path(post) %></h3>
      <% if post.user.fullname == nil || post.user.fullname == "" %>
        <h6>By <a href="users/<%=post.user['id']%>"><%= post.user.email %></a> | Posted on <%= post.created_at.to_date %> | Comments: <%= post.comments.count %> </h6>
      <%else%>
        <h6>By <a href="users/<%=post.user['id']%>"><%= post.user.fullname %></a> | Posted on <%= post.created_at.to_date %> | Comments: <%= post.comments.count %> </h6>
      <%end%>
      <p class="lead"><%= truncate post.content, length: 300 %></p>
      <%= link_to 'Read More', post %>
    </article>
    <div class="midDivider"></div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render "navbar" %>

<div class="container post">
<%= link_to "&larr; Back".html_safe, posts_path %>
  <% if current_user %>
    <h3>New Post</h3>
    <%= render "form" %>
  <%else%>
    <h3><%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %> to create a new post!</h3>
  <%end%>
</div>

app/views/posts/show.html.erb
<%= render "navbar" %>

<div class="container post">

  <%= link_to "&larr; Back".html_safe, posts_path %>

  <article>

    <h3><%= @post.title %></h3>

    <% if @post.user.fullname == nil || @post.user.fullname == "" %>
      <h6>By <a href="/users/<%=@post.user['id']%>"><%= @post.user.email %></a> | Posted on <%= @post.created_at.to_date %></h6>
    <%else%>
      <h6>By <a href="/users/<%=@post.user['id']%>"><%= @post.user.fullname %></a> | Posted on <%= @post.created_at.to_date %></h6>
    <%end%>

    <p class="lead"><%= @post.content %></p>

    <% if @post.image_upload? %>
      <%= image_tag @post.image_upload.url(:croppable) %><br>
    <%end%>

      <% if current_user %>
        <% if current_user.id == @post.user_id %>
          <%= link_to "Edit | ", edit_post_path(@post) unless @post.created_at < 1.hour.ago %>
          <%= link_to "Delete", post_path(@post), method: :delete %>
        <%end%>
      <%end%>

    <div class="divider"></div>

    <h4><%= @post.comments.count %> Replies</h4>

    <% if current_user %>
      <%= form_for [@post, Comment.new] do |f| %>
        <div class="emoji-picker-container">
          <%= f.text_area :content, placeholder: "Add a comment", class: 'form-control', data: {emojiable: true} %>
        </div><br>
        <%= f.submit "Add Comment", :class => "btn btn-default" %><br>
      <% end %>
    <%else%>
      <h6><%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %> to add a comment!</h6>
    <%end%>

    <ul>
      <%= render(partial: 'comments/comment', collection: @post.comments) %>
    </ul>

  </article>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>


  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :fullname, class: 'form-control' %><br>
    <%= f.label :bio %><br>
    <%= f.text_field :bio, class: 'form-control' %><br>
    <%= f.label :contact %><br>
    <%= f.text_field :email, class: 'form-control' %><br>
    <%= f.file_field :avatar %>
  </div>

  <%= f.submit "Update", :class => "btn btn-default" %>

<% end %>

app/views/users/edit.html.erb
<%= render "posts/navbar" %>

<div class="container">

<%= link_to "&larr; Back".html_safe, user_path %>

  <% if current_user %>
    <% if current_user.fullname == "" || current_user.fullname == nil %>
      <h3><%= "Hi There!" %></h3>
    <%else%>
      <h3><%= "Hi, #{current_user.fullname}" %></h3>
    <%end%>

    <div class="divider"></div>

    <%= render "form" %>

    <div class="divider"></div>

    <%= link_to "Sign Out", "/signout" %> <br>


  <% else %>
    <%= link_to "Sign in with Twitter", "/auth/twitter" %>
  <% end %>

</div>

app/views/users/index.html.erb
<%= render "posts/navbar" %>

<div class="container">

  <%= link_to "&larr; Back".html_safe, posts_path %>

  <h3> View Users </h3>
  <div class="divider"></div>

  <% @users.each do |user| %>
    <div class="user">
      <h6>Name: </h6><a href="users/<%=user['id']%>"> <%= user['fullname']%></a><br>
      <h6>Contact: </h6> <%= user['email'] %><br>
      <h6>Bio: </h6> <%= user['bio'] %><br>
      <div class="divider"></div>
    </div>
  <% end %>

</div>

app/views/users/new.html.erb
<%= render "posts/navbar" %>

<div class="profile">

<h1>Sign in with:</h1>

<%= link_to "Sign in", new_user_session_path %>
<a href="" class="button">Twitter</a>

<h1>Sign up with:</h1>

<%= link_to "Sign up", new_user_registration_path %>
<a href="" class="button">Twitter</a>


</div>

app/views/users/show.html.erb
<%= render "posts/navbar" %>

<div class="container user">

<%= link_to "&larr; Back".html_safe, users_path %>

<% if current_user %>
  <% if @user['id'] == current_user.id %>

    <% if current_user.fullname == "" || current_user.fullname == nil %>
      <h3><%= "Hi There!" %></h3>
    <%else%>
      <h3><%= "Hi, #{current_user.fullname}" %></h3>
    <%end%>

    <div>
      <h5><a href ="<%=current_user.id%>/edit">Edit Profile</a></h5>
    </div>

  <%end%>

  <% if @user['id'] != current_user.id %>
    <h3><%= @user['fullname'] %></h3>
  <% end %>

<%else%>
  <h3><%= @user['fullname'] %></h3>

<% end %>

  <div class="divider"></div>


    <h6>Full Name: </h6> <%= @user['fullname'] %><br>
    <h6>Bio:</h6> <%= @user['bio'] %><br>
    <h6>Contact:</h6> <%= @user['email'] %><br>
    <% if @user['id'] == current_user.id %>
      <h6><%= link_to 'Check your inbox', conversations_path %></h6><br>
    <%else%>
      <h6><%= link_to 'Message user!', conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: 'post'%></h6><br>
    <%end%>
    <% if @user.avatar? %>
      <%= image_tag @user.avatar.url(:medium) %>
    <%end%>

  <div class="divider"></div>

  <% if current_user %>
    <% if @user['id'] == current_user.id %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    <% end %>
  <% end %>

</div>